# Generated by Django 3.1.6 on 2021-02-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_korisnika', models.CharField(max_length=11, unique=True)),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Korisnici',
            },
        ),
        migrations.CreateModel(
            name='Prostorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra_prostorije', models.CharField(max_length=9, unique=True)),
                ('kat', models.CharField(max_length=15)),
                ('broj_prostorije', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Prostorije',
            },
        ),
        migrations.CreateModel(
            name='Zgrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra_zgrade', models.CharField(max_length=9, unique=True)),
                ('adresa', models.CharField(max_length=50)),
                ('subnet', models.CharField(max_length=20)),
                ('id_lokacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eroapp.lokacija')),
            ],
            options={
                'verbose_name_plural': 'Zgrade',
            },
        ),
        migrations.CreateModel(
            name='Uredaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=15, unique=True)),
                ('serijski_broj', models.CharField(max_length=20, unique=True)),
                ('vrsta_uredaja', models.CharField(choices=[('PC', 'PC'), ('Monitor', 'Monitor'), ('Printer', 'Printer'), ('Laptop', 'Laptop'), ('Telefon', 'Telefon'), ('Server', 'Server'), ('Storage', 'Storage'), ('Mreža', 'Mreža')], max_length=50)),
                ('proizvodac', models.CharField(choices=[('HP', 'HP'), ('DELL', 'DELL'), ('Lenovo', 'Lenovo'), ('Lexmark', 'Lexmark'), ('Cisco', 'Cisco')], max_length=30)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('mac_adresa', models.CharField(blank=True, max_length=30)),
                ('opis', models.TextField(blank=True, max_length=1000)),
                ('napomena', models.TextField(blank=True, max_length=1000)),
                ('datum_nabave', models.DateField(blank=True)),
                ('datum_isteka_garancije', models.DateField(blank=True)),
                ('id_prostorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eroapp.prostorija')),
                ('korisnik_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eroapp.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Uredaji',
            },
        ),
        migrations.AddField(
            model_name='prostorija',
            name='id_zgrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eroapp.zgrada'),
        ),
        migrations.CreateModel(
            name='Kvar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kvara', models.CharField(max_length=20, unique=True)),
                ('opis_kvara', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('U tijeku', 'U tijeku'), ('Rijesen', 'Rijesen'), ('Nerijesivo', 'Nerijesivo')], max_length=50)),
                ('barcode_uredaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eroapp.uredaj')),
            ],
            options={
                'verbose_name_plural': 'Kvarovi',
            },
        ),
    ]
